### ISSUE TITLE
Using Graphviz to visualize tree structure within PNode on Python

### ISSUE THREAD

**Issue by meteora9479** [iesl/xcluster#4]
Hi. I would like to visualize the tree structure on python. I also found that you have implemented the Scala 's version for visualization. Could you provide some fundamental code to implement Python's version for visualization? I would very appreciate it.

**Comment by akobre01** [comment]
Hello @meteora9479,
I've just pushed some code to support writing out Graphviz trees in python. Let me know if it works for you!

**Comment by meteora9479** [comment]
Thank you so much, @akobre01 .

**Comment by meteora9479** [comment]
It seems to work. Thank you.
<img width="1136" alt="screen shot 2019-03-07 at 4 05 20 pm" src="https://user-images.githubusercontent.com/13112463/53941619-8985f900-40f3-11e9-8119-39f6934c748e.png">
